name: Ing. de Software (CI-CD)
on: 
  push:
    branches:
      - main
jobs:
  CI:
      runs-on: ubuntu-20.04
      container:
        image: node:16.15.0
        credentials:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASS_DOCKER }}
      steps:
        - uses: actions/checkout@v1
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v1
          with:
            node-version: '16.15.0'
        - name: Install and Test
          run: |
                npm i
                npm run test
