name: Ing. de Software (CI-CD)
on: 
  push:
    branches:
      - main
jobs:
  CI:
      runs-on: ubuntu-20.04
      container:
        image: node:16.15.0
        credentials:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASS_DOCKER }}
      steps:
        - uses: actions/checkout@v1
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v1
          with:
            node-version: '16.15.0'
        - name: Install and Test
          run: |
                npm i
                npm run test

  CD:
    runs-on: ubuntu-18.04
    needs: CI

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.USER_DOCKER }} -p ${{ secrets.PASS_DOCKER }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.USER_DOCKER }}/app:latest

  toDeploy:
    name: to Production
    needs: CD
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: "alejandroocampo64@yahoo.com.ar"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "entrega-ingsoft"